### ISSUE TITLE
Include pop-over or description of column info.

### ISSUE THREAD

**Issue by j9recurses** [DataSF/open-data-explorer#36] opened 2016-05-23 18:36 UTC
EX: Need to provide column descriptions somewhere to help user understand what data they are looking at.  For instance, would be rad to describe what sector gpc detail is
<img width="1280" alt="screen shot 2016-05-23 at 11 33 21 am" src="https://cloud.githubusercontent.com/assets/6549842/15480443/78b9cdf4-20da-11e6-8075-39ff7ec0e993.png">

**Comment by jasonlally** [comment] 2016-12-05 18:14
This appears to be a duplicate of #110 but slightly more defined. I'll keep this one open for now and close the other.

**Comment by jasonlally** [comment] 2016-12-05 18:16
Disregard above, #110 is about the table preview. They'll likely be served by the same metadata infrastructure so we might want to turn these into a user story, but I'll keep them open for now.

**Comment by jasonlally** [comment] 2017-06-19 16:03
Popover definitions for fields implemented, could be improved, but closing this. We can add a new issue with more specific refinements after user feedback.

**Closed by jasonlally** 2017-06-19 16:03 UTC
Labels: enhancement
